### ISSUE TITLE
Data table not found

### ISSUE THREAD

**Issue by sqlsolver** [ankicommunity/docker-anki-sync-server#16]
* **AnkiDesktop version number:**
* **AnkiDroid version number:**

## Summary

Reproduction (what did you do - the more details you give, the better):
Deployed to Azure app service with no changed to the docker-compose other than changing the volume binds to use app service storage.

What was expected to happen:
An Anki app would appear at its assigned URL.

What happened instead (the more details you give, the better):
The web page displays, 'A server error occurred.  Please contact the administrator.' From the log below it appears a referenced SQLlite table is not found:
````
2020-11-30T12:26:06.114397919Z: [ERROR]      cursor.execute(self.fs("SELECT skey, username, path FROM session WHERE hkey=?"), (hkey,))
2020-11-30T12:26:06.114401819Z: [ERROR]  sqlite3.OperationalError: no such table: session
2020-11-30T12:26:06.116739669Z: [ERROR]  [2020-11-30 12:26:06,116]:INFO:ankisyncd.http:172.16.32.1 "GET /favicon.ico HTTP/1.1" 500 59
2020-11-30T12:26:14.727875828Z: [ERROR]  Traceback (most recent call last):
2020-11-30T12:26:14.727901729Z: [ERROR]    File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
2020-11-30T12:26:14.727907029Z: [ERROR]      self.result = application(self.environ, self.start_response)
2020-11-30T12:26:14.727911029Z: [ERROR]    File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
2020-11-30T12:26:14.727915029Z: [ERROR]      resp = self.call_func(req, *args, **kw)
2020-11-30T12:26:14.727918629Z: [ERROR]    File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
2020-11-30T12:26:14.727922629Z: [ERROR]      return self.func(req, *args, **kwargs)
2020-11-30T12:26:14.727926229Z: [ERROR]    File "/app/anki-sync-server/ankisyncd/sync_app.py", line 506, in __call__
2020-11-30T12:26:14.727941529Z: [ERROR]      session = self.session_manager.load(hkey, self.create_session)
2020-11-30T12:26:14.727944929Z: [ERROR]    File "/app/anki-sync-server/ankisyncd/sessions.py", line 76, in load
2020-11-30T12:26:14.727948330Z: [ERROR]      cursor.execute(self.fs("SELECT skey, username, path FROM session WHERE hkey=?"), (hkey,))
2020-11-30T12:26:14.727963730Z: [ERROR]  sqlite3.OperationalError: no such table: session
2020-11-30T12:26:14.730837290Z: [ERROR]  [2020-11-30 12:26:14,730]:INFO:ankisyncd.http:172.16.32.1 "GET / HTTP/1.1" 500 59
2020-11-30T12:26:14.850312980Z: [ERROR]  Traceback (most recent call last):
2020-11-30T12:26:14.850338880Z: [ERROR]    File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
2020-11-30T12:26:14.850344180Z: [ERROR]      self.result = application(self.environ, self.start_response)
2020-11-30T12:26:14.850349481Z: [ERROR]    File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
2020-11-30T12:26:14.850353281Z: [ERROR]      resp = self.call_func(req, *args, **kw)
2020-11-30T12:26:14.850363181Z: [ERROR]    File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
2020-11-30T12:26:14.850367781Z: [ERROR]      return self.func(req, *args, **kwargs)
2020-11-30T12:26:14.850371081Z: [ERROR]    File "/app/anki-sync-server/ankisyncd/sync_app.py", line 506, in __call__
2020-11-30T12:26:14.850374681Z: [ERROR]      session = self.session_manager.load(hkey, self.create_session)
2020-11-30T12:26:14.850378081Z: [ERROR]    File "/app/anki-sync-server/ankisyncd/sessions.py", line 76, in load
2020-11-30T12:26:14.850388981Z: [ERROR]      cursor.execute(self.fs("SELECT skey, username, path FROM session WHERE hkey=?"), (hkey,))
2020-11-30T12:26:14.850392881Z: [ERROR]  sqlite3.OperationalError: no such table: session
2020-11-30T12:26:14.851792811Z: [ERROR]  [2020-11-30 12:26:14,851]:INFO:ankisyncd.http:172.16.32.1 "GET /favicon.ico HTTP/1.1" 500 59
````

**Comment by kuklinistvan** [comment]
Hello,

> An Anki app would appear at its assigned URL.

I need some more information. What request did you send to what URL?

> The web page displays, 'A server error occurred. Please contact the administrator.' 

There is no web page to load, as this server is not a web application, but an API.

**Comment by kuklinistvan** [comment]
I'm closing this due to inactivity. Feel free to reopen it later!
